# Generated by Django 3.1 on 2020-11-30 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaitoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='バイト先の名前')),
                ('base', models.IntegerField(default=0, verbose_name='基本給')),
                ('plus_evening', models.IntegerField(default=100, verbose_name='夕方手当')),
                ('plus_night', models.IntegerField(default=25, verbose_name='深夜割増')),
                ('plus_holiday', models.IntegerField(default=150, verbose_name='祝日手当')),
                ('plus_overtime', models.IntegerField(default=25, verbose_name='8時間労働時の残業割増')),
            ],
        ),
        migrations.CreateModel(
            name='CoursesTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='履修科目名')),
                ('CT_status', models.IntegerField(choices=[(2, '月曜日'), (3, '火曜日'), (4, '水曜日'), (5, '木曜日'), (6, '金曜日'), (7, '土曜日')], verbose_name='曜日')),
                ('period', models.IntegerField(choices=[(1, '１限'), (2, '2限'), (3, '3限'), (4, '4限'), (5, '5限'), (6, '6限'), (7, '7限')], verbose_name='時限')),
                ('URLURL', models.CharField(default='#', max_length=100, verbose_name='授業用URL')),
                ('school_credit', models.IntegerField(default=0, verbose_name='単位数')),
            ],
        ),
        migrations.CreateModel(
            name='KadaiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='課題名')),
                ('date', models.DateTimeField(default='2020-11-30 23:44', verbose_name='提出期日')),
                ('overview', models.CharField(max_length=1000, verbose_name='概要')),
                ('display', models.IntegerField(choices=[(0, '使用'), (1, '使用しない')], default=0, verbose_name='表示・非表示')),
                ('submit_date', models.DateTimeField(null=True, verbose_name='提出した日')),
                ('CT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kadai_info', to='mysite.coursestaken', verbose_name='科目')),
            ],
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='テスト名')),
                ('date', models.DateTimeField(verbose_name='テスト日')),
                ('overview', models.CharField(max_length=1000, verbose_name='概要')),
                ('CT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='mysite.coursestaken', verbose_name='科目')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0, verbose_name='このテストで取得した点数')),
                ('status', models.IntegerField(choices=[(0, '未受験'), (1, '受験済み')], verbose_name='提出状況')),
                ('TI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test_info', to='mysite.testinfo', verbose_name='テスト')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='UserKadaiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0, verbose_name='この課題で取得した点数')),
                ('status', models.IntegerField(choices=[(0, '未提出'), (1, '提出済')], verbose_name='提出状況')),
                ('KI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_kadai_info', to='mysite.kadaiinfo', verbose_name='課題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailaddress', models.EmailField(default='address here', max_length=255, verbose_name='メールアドレス')),
                ('address_status', models.IntegerField(choices=[(0, '無し'), (1, '仮登録'), (2, '本登録')], default=0, verbose_name='登録有無')),
                ('status', models.IntegerField(default=0, verbose_name='メール送信状態')),
                ('mail_date', models.DateTimeField(default='2020-01-01 12:00', verbose_name='メール送信日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user4', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='UserCTInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_CT', models.IntegerField(choices=[(0, '未履修'), (1, '履修中')], verbose_name='履修状態')),
                ('CT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_CT_info', to='mysite.coursestaken', verbose_name='科目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaitoTimeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(default='2020-11-30 23:44', verbose_name='出勤時間')),
                ('out_time', models.DateTimeField(default='2020-11-30 23:44', verbose_name='退勤時間')),
                ('holiday', models.IntegerField(choices=[(0, '平日'), (1, '日祝')], default=0, verbose_name='平日or日祝')),
                ('tmp_salary', models.IntegerField(default=0, verbose_name='一当たりの給料')),
                ('BI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_baito_info2', to='mysite.baitoinfo', verbose_name='バイト')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user5', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
    ]
