# Generated by Django 3.1 on 2020-11-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baitoinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='kadaiinfo',
            name='date',
            field=models.DateTimeField(default='2020-11-17 08:09', verbose_name='提出期日'),
        ),
    ]
