# Generated by Django 3.1 on 2020-09-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestaken',
            name='URLURL',
            field=models.URLField(default=' ', max_length=100, verbose_name='授業用URL'),
        ),
    ]
