# Generated by Django 3.1 on 2020-09-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_coursestaken_urlurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestaken',
            name='URLURL',
            field=models.URLField(default='', max_length=100, verbose_name='授業用URL'),
        ),
    ]
