# Generated by Django 3.1 on 2020-11-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20201117_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baitotimeinfo',
            name='in_time',
            field=models.DateTimeField(default='2020-11-17 08:11', verbose_name='出勤時間'),
        ),
        migrations.AlterField(
            model_name='baitotimeinfo',
            name='out_time',
            field=models.DateTimeField(default='2020-11-17 08:11', verbose_name='退勤時間'),
        ),
        migrations.AlterField(
            model_name='kadaiinfo',
            name='date',
            field=models.DateTimeField(default='2020-11-17 08:11', verbose_name='提出期日'),
        ),
    ]
