# Generated by Django 3.1 on 2020-11-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20201119_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='baitotimeinfo',
            name='tmp_salary',
            field=models.IntegerField(default=0, verbose_name='一当たりの給料'),
        ),
        migrations.AlterField(
            model_name='baitotimeinfo',
            name='in_time',
            field=models.DateTimeField(default='2020-11-19 14:12', verbose_name='出勤時間'),
        ),
        migrations.AlterField(
            model_name='baitotimeinfo',
            name='out_time',
            field=models.DateTimeField(default='2020-11-19 14:12', verbose_name='退勤時間'),
        ),
        migrations.AlterField(
            model_name='kadaiinfo',
            name='date',
            field=models.DateTimeField(default='2020-11-19 14:12', verbose_name='提出期日'),
        ),
    ]
