# Generated by Django 3.1 on 2020-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200928_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestaken',
            name='URLURL',
            field=models.CharField(default='#', max_length=100, verbose_name='授業用URL'),
        ),
    ]
