# Generated by Django 3.1 on 2020-10-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20201010_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mail_date',
            field=models.DateTimeField(default='2020-01-01 12:00', verbose_name='メール送信日'),
        ),
    ]
